name: rlds_env
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip
  - matplotlib
  - h5py
  - pip:
      - tensorflow==2.13.1
      - tensorflow-datasets
      - tensorflow-hub
      - apache-beam
      - plotly
      - wandb